#!/usr/bin/env bash
set -euo pipefail

# BlackRoad Infrastructure Audit
# Produces raw counts. No scores. No percentages. Just truth.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.json"
OUTPUT_FILE="${SCRIPT_DIR}/STATUS.md"

ACTIVITY_WINDOW_DAYS=30
TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
CUTOFF_DATE="$(date -u -d "${ACTIVITY_WINDOW_DAYS} days ago" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u -v-${ACTIVITY_WINDOW_DAYS}d +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")"

# Parse config
ORGS=$(jq -r '.organizations[]' "$CONFIG_FILE")
DOMAINS=$(jq -r '.domains[]' "$CONFIG_FILE")

ORG_TOTAL=0
ORG_VERIFIED=0
ORG_ACTIVE=0
DOMAIN_TOTAL=0
DOMAIN_RESOLVING=0
HTTPS_OK=0
SSL_VALID=0

ENTERPRISE_REACHABLE="No"

# Check if GitHub API is reachable
if curl -sf --max-time 10 "https://api.github.com/zen" > /dev/null 2>&1; then
  ENTERPRISE_REACHABLE="Yes"
fi

# GitHub auth header (optional)
AUTH_HEADER=""
if [ -n "${GITHUB_TOKEN:-}" ]; then
  AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
fi

github_api() {
  local url="$1"
  if [ -n "$AUTH_HEADER" ]; then
    curl -sf --max-time 15 -H "$AUTH_HEADER" "$url" 2>/dev/null
  else
    curl -sf --max-time 15 "$url" 2>/dev/null
  fi
}

# --- Organization Checks ---

ORG_RESULTS=""

for org in $ORGS; do
  ORG_TOTAL=$((ORG_TOTAL + 1))
  verified="no"
  active="no"

  # Verified: GitHub API returns 200 and org exists
  response=$(github_api "https://api.github.com/orgs/${org}")
  if [ -n "$response" ]; then
    verified="yes"
    ORG_VERIFIED=$((ORG_VERIFIED + 1))

    # Active: at least one repo updated in last 30 days
    if [ -n "$CUTOFF_DATE" ]; then
      repos=$(github_api "https://api.github.com/orgs/${org}/repos?sort=updated&per_page=1")
      if [ -n "$repos" ]; then
        last_updated=$(echo "$repos" | jq -r '.[0].updated_at // empty' 2>/dev/null)
        if [ -n "$last_updated" ] && [[ "$last_updated" > "$CUTOFF_DATE" ]]; then
          active="yes"
          ORG_ACTIVE=$((ORG_ACTIVE + 1))
        fi
      fi
    fi
  fi

  ORG_RESULTS="${ORG_RESULTS}| ${org} | ${verified} | ${active} |\n"
done

# --- Domain Checks ---

DOMAIN_RESULTS=""

for domain in $DOMAINS; do
  DOMAIN_TOTAL=$((DOMAIN_TOTAL + 1))
  resolving="no"
  https_status="-"
  ssl_status="-"

  # Resolving: DNS lookup succeeds
  if nslookup "$domain" > /dev/null 2>&1 || host "$domain" > /dev/null 2>&1 || dig +short "$domain" 2>/dev/null | grep -q .; then
    resolving="yes"
    DOMAIN_RESOLVING=$((DOMAIN_RESOLVING + 1))

    # HTTPS 200 OK: GET request returns 200
    http_code=$(curl -o /dev/null -sf --max-time 15 -w "%{http_code}" "https://${domain}" 2>/dev/null || echo "000")
    https_status="${http_code}"
    if [ "$http_code" = "200" ]; then
      HTTPS_OK=$((HTTPS_OK + 1))
    fi

    # Valid SSL: certificate expiry date > current date
    expiry=$(echo | openssl s_client -servername "$domain" -connect "${domain}:443" 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | sed 's/notAfter=//')
    if [ -n "$expiry" ]; then
      expiry_epoch=$(date -d "$expiry" +%s 2>/dev/null || date -j -f "%b %d %T %Y %Z" "$expiry" +%s 2>/dev/null || echo "0")
      now_epoch=$(date +%s)
      if [ "$expiry_epoch" -gt "$now_epoch" ] 2>/dev/null; then
        ssl_status="valid"
        SSL_VALID=$((SSL_VALID + 1))
      else
        ssl_status="expired"
      fi
    else
      ssl_status="no cert"
    fi
  fi

  DOMAIN_RESULTS="${DOMAIN_RESULTS}| ${domain} | ${resolving} | ${https_status} | ${ssl_status} |\n"
done

# --- Generate STATUS.md ---

cat > "$OUTPUT_FILE" <<EOF
# BlackRoad Infrastructure Status

\`\`\`
Enterprise Reachable:          ${ENTERPRISE_REACHABLE}
Organizations Verified:        ${ORG_VERIFIED} / ${ORG_TOTAL}
Active Organizations (30d):    ${ORG_ACTIVE} / ${ORG_TOTAL}
Domains Resolving:             ${DOMAIN_RESOLVING} / ${DOMAIN_TOTAL}
HTTPS 200 OK:                  ${HTTPS_OK} / ${DOMAIN_TOTAL}
Valid SSL Certificates:        ${SSL_VALID} / ${DOMAIN_TOTAL}
Last Audit:                    ${TIMESTAMP}
\`\`\`

## Organization Detail

| Organization | Verified | Active (30d) |
|---|---|---|
$(echo -e "$ORG_RESULTS")

## Domain Detail

| Domain | Resolving | HTTPS Status | SSL |
|---|---|---|---|
$(echo -e "$DOMAIN_RESULTS")

---

*Generated by [infrastructure/audit.sh](infrastructure/audit.sh) at ${TIMESTAMP}*
EOF

# --- Also print to stdout ---

echo ""
echo "BlackRoad Infrastructure Status"
echo "================================"
echo ""
echo "Enterprise Reachable:          ${ENTERPRISE_REACHABLE}"
echo "Organizations Verified:        ${ORG_VERIFIED} / ${ORG_TOTAL}"
echo "Active Organizations (30d):    ${ORG_ACTIVE} / ${ORG_TOTAL}"
echo "Domains Resolving:             ${DOMAIN_RESOLVING} / ${DOMAIN_TOTAL}"
echo "HTTPS 200 OK:                  ${HTTPS_OK} / ${DOMAIN_TOTAL}"
echo "Valid SSL Certificates:        ${SSL_VALID} / ${DOMAIN_TOTAL}"
echo "Last Audit:                    ${TIMESTAMP}"
echo ""
echo "Full report written to: ${OUTPUT_FILE}"
